### ISSUE TITLE
java.lang.IllegalStateException: Cannot modify server settings off of the global region

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [ricsal1/CoolProtection#1]
Hi, I had an error while using your plugin on Folia that caused it to not load, maybe this is a bug?
---------------------------------
Logs: https://paste.ubuntu.com/p/bmCkpqZmMm/
---------------------------------

**Comment by ricsal1** [comment]
> ## Hi, I had an error while using your plugin on Folia that caused it to not load, maybe this is a bug?
> ## Logs: https://paste.ubuntu.com/p/bmCkpqZmMm/

Thanks m8, will look into it tomorrow. Guess it is something we can't do on Folia, that I have missed.

**Comment by xiaoyueyoqwq** [comment]
> > ## Hi, I had an error while using your plugin on Folia that caused it to not load, maybe this is a bug?
> > ## Logs: https://paste.ubuntu.com/p/bmCkpqZmMm/
> 
> Thanks m8, will look into it tomorrow. Guess it is something we can't do on Folia, that I have missed.

okay, waiting for you in anytime❤️

**Comment by ricsal1** [comment]
You can bypass the problem if, before starting the server, you change the plugin config to 70  "maxChunkEntities: 70"

**Comment by xiaoyueyoqwq** [comment]
> You can bypass the problem if, before starting the server, you change the plugin config to 70  "maxChunkEntities: 70"

Okay I will try it now

**Comment by xiaoyueyoqwq** [comment]
> You can bypass the problem if, before starting the server, you change the plugin config to 70 "maxChunkEntities: 70"

Hey, I think it doesn't work...This is server's full log and maybe it can help you to find bug?
---------------------------------------
https://paste.ubuntu.com/p/BkY2jXDCHq/
---------------------------------------

And this is your plugin's config
---------------------------------------
https://paste.ubuntu.com/p/7HHtTbs6r2/
---------------------------------------

**Comment by ricsal1** [comment]
You are right, with that config it shouldn't give error, but you have server settings changed:
"SpawnLimit value changed from **30** to 70"

Have a try on this version, should handle it well

https://modrinth.com/plugin/coolprotection/version/1.7.7

**Comment by xiaoyueyoqwq** [comment]
> You are right, with that config it shouldn't give error, but you have server settings changed:
> "SpawnLimit value changed from **30** to 70"
> 
> Have a try on this version, should handle it well
> 
> https://modrinth.com/plugin/coolprotection/version/1.7.7

Okay, I'd try this version in today afternoon

**Comment by xiaoyueyoqwq** [comment]
> You are right, with that config it shouldn't give error, but you have server settings changed: "SpawnLimit value changed from **30** to 70"
> 
> Have a try on this version, should handle it well
> 
> https://modrinth.com/plugin/coolprotection/version/1.7.7

It's good that the plugin has been fixed by you, thanks for your help ❤
But I hope you can add some features separately, such as creeper explosion protection, cultivated land anti-trampling, etc., which may not be so important for TNT explosion protection, because some Redstone machines must rely on TNT explosion to function properly

**Comment by ricsal1** [comment]
First of all, thank you, since you have detected something that I have missed on the tests. 
Good projects are achieved from all the people around it, with the ideas and reports, and not only the creator typing the code :). 

> But I hope you can add some features separately, such as creeper explosion protection, cultivated land anti-trampling, etc., which may not be so important for TNT explosion protection, because some Redstone machines must rely on TNT explosion to function properly

This plugin was mainly intended to protect the server stability by avoiding common hacks/attacks and disruptions like lag machines, major explosions,... and keeping the world as survival as possible and aiming to require as low configuration as possible.

What you commented seems more like anti grief that isn't **yet** the purpose of this project.

Can you give me an example of a tnt redstone machine you need to keep working?

**Comment by xiaoyueyoqwq** [comment]
> First of all, thank you, since you have detected something that I have missed on the tests. Good projects are achieved from all the people around it, with the ideas and reports, and not only the creator typing the code :).
> 
> > But I hope you can add some features separately, such as creeper explosion protection, cultivated land anti-trampling, etc., which may not be so important for TNT explosion protection, because some Redstone machines must rely on TNT explosion to function properly
> 
> This plugin was mainly intended to protect the server stability by avoiding common hacks/attacks and disruptions like lag machines, major explosions,... and keeping the world as survival as possible and aiming to require as low configuration as possible.
> 
> What you commented seems more like anti grief that isn't **yet** the purpose of this project.
> 
> Can you give me an example of a tnt redstone machine you need to keep working?

First of all thanks for your reply, I want to clarify that I don't want anti-GRIEF, I mean maybe we can add more anti-GRIEF content such as creeper blast protection and other more configurable options, which will help the server Admin better set up server functions
